"""Shared helpers for the media pipeline: frame grabbing (ffmpeg), crop/grade, export (AVIF/WebP/JPG), media.js writer.
Pillow is already installed on this machine; encoders are Pillow's libavif/libwebp/libjpeg (ffmpeg is used for video + frames)."""
import os, re, subprocess
import numpy as np
from PIL import Image, ImageFilter

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), '..', '..'))
PUB = f'{ROOT}/public'
WORK = f'{ROOT}/.shots/media-work'
INK = (22, 20, 20)  # --ink #161414

AVIF_Q, WEBP_Q, JPG_Q = 62, 78, 82


def src_path(v):
    if v.startswith('ig:'): return f'{ROOT}/insumos/ig/reels/{v[3:]}.mp4'
    return f'{ROOT}/insumos/youtube/{v}.mp4'


def frame(v, t):
    """Full-resolution lossless frame at the exact timestamp (cached). 'img:<file>' loads a still from insumos/web."""
    if v.startswith('img:'): return Image.open(f'{ROOT}/insumos/web/{v[4:]}').convert('RGB')
    os.makedirs(f'{WORK}/full', exist_ok=True)
    f = f'{WORK}/full/{v.replace(":", "_")}_{float(t):07.2f}.png'
    if not os.path.exists(f):
        subprocess.run(['ffmpeg', '-v', 'error', '-y', '-ss', str(t), '-i', src_path(v), '-frames:v', '1', f], check=True)
    return Image.open(f).convert('RGB')


def grade(im, gamma=1.0, contrast=1.0, sat=1.0, warm=0.0, lift_black=False, black=0, copyrow=None):
    """Gentle correction. gamma<1 brightens; warm>0 pushes R up / B down a few levels; lift_black maps pure black to --ink."""
    a = np.asarray(im).astype(np.float32) / 255
    if copyrow: y, x0, x1 = copyrow; a[y, x0:x1] = a[y - 1, x0:x1]  # hide a 1 px seam baked into the source
    if black: a = np.clip((a - black / 255) / (1 - black / 255), 0, 1)  # crush compression noise in the blacks
    if gamma != 1.0: a = a ** gamma
    if contrast != 1.0: a = (a - 0.5) * contrast + 0.5
    if sat != 1.0:
        g = a.mean(axis=2, keepdims=True); a = g + (a - g) * sat
    if warm: a[..., 0] += warm * 0.02; a[..., 2] -= warm * 0.02
    if lift_black:
        ink = np.array(INK, dtype=np.float32) / 255
        a = ink + a * (1 - ink)
    return Image.fromarray((np.clip(a, 0, 1) * 255 + 0.5).astype(np.uint8))


def save_set(im, base, w, quality=(AVIF_Q, WEBP_Q, JPG_Q), flatten=None):
    """Write public/<base>-<w>.{avif,webp,jpg} for one already-resized image (RGBA is flattened onto `flatten` for the JPG)."""
    p = f'{PUB}/{base}-{w}'
    os.makedirs(os.path.dirname(p), exist_ok=True)
    im.save(f'{p}.avif', quality=quality[0], speed=5)
    im.save(f'{p}.webp', quality=quality[1], method=4 if im.mode == 'RGBA' else 6)  # method 6 + alpha is pathologically slow
    j = im
    if im.mode == 'RGBA':
        j = Image.new('RGB', im.size, flatten or (255, 255, 255)); j.paste(im, mask=im.split()[3])
    j.save(f'{p}.jpg', quality=quality[2], progressive=True, optimize=True)


def export(im, base, widths, sharpen=True, **kw):
    """Resize (never upscale) to each width and write all three formats. Returns the media.js entry fragment."""
    ws = sorted({min(w, im.width) for w in widths})
    for w in ws:
        h = round(im.height * w / im.width)
        r = im if w == im.width else im.resize((w, h), Image.LANCZOS)
        if sharpen and w != im.width: r = r.filter(ImageFilter.UnsharpMask(radius=0.7, percent=35, threshold=2))
        save_set(r, base, w, **kw)
    return {'base': base, 'widths': ws, 'w': ws[-1], 'h': round(im.height * ws[-1] / im.width)}


def crop_to(im, box, aspect=None):
    """box = (x0, y0, x1, y1) in source pixels. Optional aspect check (w/h) with 1% tolerance, for safety."""
    c = im.crop(box)
    if aspect: assert abs(c.width / c.height - aspect) / aspect < 0.01, (c.size, aspect)
    return c


# ---- media.js writer ----
def _key(k): return k if re.fullmatch(r'[A-Za-z_$][\w$]*', str(k)) else f"'{k}'"


def _val(v, ind):
    pad = '  ' * ind
    if isinstance(v, dict):
        if all(not isinstance(x, (dict, list)) for x in v.values()):
            return '{ ' + ', '.join(f'{_key(k)}: {_val(x, 0)}' for k, x in v.items()) + ' }'
        return '{\n' + ',\n'.join(f'{pad}  {_key(k)}: {_val(x, ind + 1)}' for k, x in v.items()) + f'\n{pad}}}'
    if isinstance(v, list):
        if all(not isinstance(x, (dict, list)) for x in v): return '[' + ', '.join(_val(x, 0) for x in v) + ']'
        return '[\n' + ',\n'.join(f'{pad}  {_val(x, ind + 1)}' for x in v) + f'\n{pad}]'
    if isinstance(v, bool): return 'true' if v else 'false'
    if isinstance(v, (int, float)): return str(v)
    return "'" + str(v).replace('\\', '\\\\').replace("'", "\\'") + "'"


def write_media_js(media, path):
    head = ("// Generated by tools/media/build.py: do not edit by hand.\n"
            "// Contract: every image lives at public/<base>-<width>.{avif,webp,jpg}; w/h = size of the widest variant.\n"
            "// Loops: { base, video: true, poster } -> public/<base>.mp4 + .webm.\n")
    os.makedirs(os.path.dirname(path), exist_ok=True)
    open(path, 'w', encoding='utf-8', newline='\n').write(head + 'export const media = ' + _val(media, 0) + ';\n')
